title: Runbooks
description: description for the site goes here
author: myTeam
lang: en

remote_theme: rundocs/jekyll-rtd-theme

copyright:
  # since: 2020
  revision: true

edit: true
addons_branch: false
addons: false

readme_index:
  with_frontmatter: true

exclude:
  - Gemfile
  - Gemfile.lock
